language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: NqQnD838jkrZYdEdVBigS1nKaYDwf1u9mWidxenU+wE2/PLSYz8yO/mD9XTy1uaAji6yazNN/odQinIukcUr0rAGcFoxZg93GiXLGuLBosgUKx9OHm2IThOimhPoUjeoR2BcqA/EV7bordLTNHnM5ZCg4uQkasIIDZFZk7lPx9w=
  - secure: JvJcNdcbec8ybGIXj7jGAzQiayeGPWxXzOKm7Ek7T0qg1O7aozqWl3qX+VcH5Q0wiLlhtJjshjhCn3FT0CW/ART3AyKt3rmYvujERYVapIFAfceI/4aHFuUfryOYlunHF58+STOKWrDAaotxk/yeILBB4kQMLSFgm2B3f/iAuUU=
