<div class="table-responsive">
    <table class="table table-hover">
        <tbody>
        <tr>
            <th>Bytes sent total:</th>
            <td>$bytesSent$</td>
        </tr>
        <tr>
            <th>Messages per second:</th>
            <td>$msgPerSec$</td>
        </tr>
        <tr>
            <th>Open connections:</th>
            <td>$openConnections$</td>
        </tr>
        <tr>
            <th>Max open connections:</th>
            <td>$maxOpenConnections$</td>
        </tr>
        <tr>
            <th>Number of datasets:</th>
            <td>$noDataSets$</td>
        </tr>
        <tr>
            <th>Total size of datasets:</th>
            <td>$sizeDataSets$</td>
        </tr>
        </tbody>
    </table>
</div>